Multiple payments benchmark
interledger-rs/interledger-rs pull request #663
Opened 2020-12-04 14:46 UTC by KristianWahlroos

Add a benchmark that tracks, how long it takes for a ilp-node to receive payment through websocket, process it and respond back.

```bash #
# This runs the multiple payments benchmark
cargo bench -- multiple_payments
```

2020-12-16 18:27 UTC, aphelionz commented
I would personally love a nice benchmarking foundation and would love to hear others thoughts on it :)

GitHub suggested @dora-gt and @emschwartz, let it be so

2021-01-07 15:43 UTC, KristianWahlroos commented
`Benchmarking process_payment (Low packet count): Warming up for 3.0000 sJan 07 00:26:45.942 ERROR interledger_router::router: No route found for request : IncomingRequest { prepare: Prepare { destination: Address("example.parent.bob_on_b.V1kI5fLTy-alvd6LFsFOUqDT"), amount: 1, expires_at: "2021-01-06T22:27:14.895+00:00", execution_condition: "cd8e7a6fd001e5c5d493a317937ec3424bafe3bd472237628669c2445cb2dcb9", data_length: 77 }, from: Account { id: 3a931422-a39d-402b-9fa1-d7f20dc259df, username: Username("a_on_b"), ilp_address: Address("example.parent.a_on_b"), asset_code: "XYZ", asset_scale: 9, max_packet_amount: 18446744073709551615, min_balance: None, ilp_over_http_url: None, ilp_over_http_incoming_token: None, ilp_over_http_outgoing_token: None, ilp_over_btp_url: None, ilp_over_btp_incoming_token: Some(SecretBytesMut([REDACTED])), ilp_over_btp_outgoing_token: None, settle_threshold: None, settle_to: None, routing_relation: Child, round_trip_time: 500, packets_per_minute_limit: None, amount_per_minute_limit: None, settlement_engine_url: None } }
Jan 07 00:26:45.942 ERROR interledger_stream::client: Send money stopped because of error: SendMoneyError("Packet was rejected with error: F02 ")
Jan 07 00:26:45.942 ERROR interledger_spsp::client: Error sending payment: SendMoneyError("Packet was rejected with error: F02 ")
Jan 07 00:26:45.942 ERROR interledger_api::routes::accounts: Error sending SPSP payment: Error sending money: 1`

Got an error message, that I am fixing

2021-01-18 12:29 UTC, koivunej approved these changes
I think this is good to go.

This will add to the duplication with the `{redis,test}_helpers.rs`. I did look into this and we can most likely split it into two unpublished dev-dependency crates in the future since the redis support is needed from a few crates, but only the ilp-node related http functions are only needed in `ilp-node`.

2021-01-21 15:17 UTC, koivunej commented
This needs to be rebased.

2021-02-11 19:49 UTC, KristianWahlroos commented
I have tried to fix `interledger_stream::crypto: Error decrypting Unspecified` error in my ilp over http benchmarks. However I noticed that this error happens in tests `three_nodes.rs` and `prometheus.rs` as well. My benchmark ilp over http version and these two tests seems to be the only occurrences that uses ilp over http instead of ilp over btp, so I am guessing that there might be something fishy going on. 🍣 The decrypting error will be fixed in an another pull request as it is not a benchmark only problem.

2021-02-18 07:21 UTC, koivunej requested changes

2021-02-18 07:21 UTC, koivunej commented on crates/ilp-node/benches/multiple_payments.rs
> +            receiver.recv().await.unwrap().into_text().unwrap();
Why does this need to do the string conversion?

2021-02-18 07:21 UTC, koivunej commented on crates/ilp-node/benches/multiple_payments.rs
> +    );
Why is this needed here instead of just doing it once after node creation?

2021-02-18 07:21 UTC, koivunej commented on crates/ilp-node/benches/multiple_payments.rs
> +    wait_for_propagation(&mut rt, &req_low, received_message_count_low, &mut receiver);
As there's no `route_broadcast_interval` for this cases Nodes I think this can sometimes time out (didn't test but that happened in my own tests).

This waiting should be guarded by a timeout not to get a hang.

2021-02-18 07:21 UTC, koivunej commented on crates/ilp-node/benches/multiple_payments.rs
> +        "route_broadcast_interval": Some(200),
I'd make the right-hand side a constant u64, use it consistently on all of these node configurations. It'd also be a great place to document why it is needed and what issues does it cause (noise to the measurements).

2021-02-18 07:21 UTC, koivunej commented on crates/ilp-node/benches/multiple_payments.rs
> +    drop(rt);
The redis testcontext nags during exit, most likely because this drops the redis connection(s). Have you tested if dropping testcontext before this would silence it? Could be that there'd just be another nag from the ilp-node side.

2021-02-18 19:25 UTC, koivunej approved these changes
Minor left-over unwrap, but I think this is looking good to go.

2021-02-18 19:25 UTC, koivunej commented on crates/ilp-node/benches/multiple_payments.rs
> +    let mut payments_ws = client::connect(ws_request).unwrap().0;
```suggestion
    let mut payments_ws = client::connect(ws_request)?.0;
```

I think this is a leftover `unwrap`.

2021-02-19 13:24 UTC, koivunej approved these changes
Oki, lets merge this after the CI finishes. This doesn't really change any behaviour but it helps with further development, so even if 24h rule applied I'm sure that has already passed.

2021-02-19 13:30 UTC, merged