fix: Clean up and decouple interledge-packet::ParseError in other crates
interledger-rs/interledger-rs pull request #722
Opened 2021-05-12 16:14 UTC by whalelephant

cc #708

2021-05-14 10:58 UTC, koivunej requested changes
Overall I think this looks very good; you updated it during my scan through, so some things might already be good to resolve.

There are some string nits; perhaps the biggest issue is with the changed messages. Are you sure those can change? I think I reverted some changes as well in the bytes 0.5 upgrade, so I'd be inclined to *keep* the external behaviour (the messages) as the same by default when refactoring.

Either way, I think at least the `interledger-packet::Error` commits need a `!` to signify a breaking change (since those at minimum are exported).

EDIT: thought about it a bit, expanded the I'd be inclined to keep the external behaviour (the messages) as the same by default when refactoring.

2021-05-14 10:58 UTC, koivunej commented on crates/interledger-packet/src/errors.rs
> +    Roundtrip,
this could be `#[cfg(feature = "roundtrip-only")]` (if supported by thiserror) also note that the error isn't *unexpected*, it's by definition expected since that's why the feature exists in the first place.

2021-05-14 10:58 UTC, koivunej commented on crates/interledger-packet/src/packet.rs
> +                return Err(ParseError::Roundtrip);
Looking at the site of use re my earlier note on this variant; `NonRoundtrippableTimestamp` would probably work even better; that way you could you peek at the `Error` type of the crate, learn about the `roundtrip-only` feature and what kind of input are not accepted when `--features roundtrip-only` (`NonRoundtrippableTimestamp` => "some timestamps are not roundtrippable").

2021-05-14 10:58 UTC, koivunej commented on crates/interledger-packet/src/packet.rs
> +        Err(TrailingBytesError::Inner)
I think this is looking really good! The correspondance of the deleted string message to the new value is clear!

2021-05-14 10:58 UTC, koivunej commented on crates/interledger-packet/src/packet.rs
> +        assert_eq!("Input data is not IA5String characters", &e.to_string());
This does make me think of the expected compatibility... I think as this crate is largely part of the API and these might even be formatted into rejects (or other protocol level things, or at the http; didn't check), did you consider keeping the prefix?

I fumbled the line selection so cannot suggest; but I'd remove the word "characters" (as in general, that term is very difficult with encodings, even though it's clear with ascii and similar).

Also, is there point in making this a general error instead of keeping it tied to the specific case where this is returned (namely `Reject.ErrorCode`).

2021-05-14 10:58 UTC, koivunej commented on crates/interledger-packet/src/packet.rs
> +            assert_eq!("Trailing Bytes Error: Inner", &res.unwrap_err().to_string(),);
I think the message could be better, but I guess with `thiserror` that flexibility is lost? `match`'ing through the both variants with in a plain rust `std::fmt::Display` would be easy.

2021-05-14 10:58 UTC, koivunej commented on crates/interledger-packet/src/packet.rs
> +            "PacketType data not found",
```suggestion
            "PacketType not found",
```
String-nit: I don't think the word `data` is meaningful here; when parsing we cannot hope to find anything but data.

2021-05-14 10:58 UTC, koivunej commented on crates/interledger-stream/src/error.rs
> +    #[error("Error maximum time exceeded since last fulfill")]
```suggestion
    #[error("Maximum time exceeded since last fulfill")]
```
Or are these variants used in non-error contexts? Note the changed prefixes altogether, in case this was used in the stream api/rejects/at some level that someone might get access to comparing the server sent messages and hardcode these.

2021-05-14 10:58 UTC, koivunej commented on crates/interledger-stream/src/error.rs
> +    Roundtrip,
```suggestion
    #[cfg(feature = "roundtrip-only")]
    #[cfg_attr(feature = "roundtrip-only", error("Roundtrip only: Error expected for roundtrip fuzzing"))]
    Roundtrip,
```

This might work?

2021-05-14 10:58 UTC, koivunej commented on crates/interledger-stream/src/packet.rs
> +            return Err(StreamPacketError::UnsupportedVersion);
Variant-note: Is the version lost on purpose?

2021-05-14 10:58 UTC, koivunej commented on crates/interledger-stream/src/packet.rs
> +            Err(StreamPacketError::Roundtrip)
Variant-note: Same thing as with `interledger-packet::Error::Roundtrip`: the meaning is now diluted away. I think there might be value in keeping it. Perhaps a `NonRoundtrippableSaturatingAmount`?

2021-05-14 10:58 UTC, koivunej commented on crates/interledger-ccp/src/packet.rs
> +    IOError,
The other variants still have `std::io::Error` inside of them. I think having an empty variant for it is a good compromise as information will be lost.

Could it be eradicated completely, since no I/O is actually done while parsing?

This would mean at least:

1. adding length checks
2. calling `bytes::Buf` methods instead of `byteorder` methods in `interledger-packet`

The first one can be tested as `bytes::Buf` methods except for `get_uint` should all panic; if I remember correctly the `get_uint` doesn't require any bytes so it doesn't panic (just returns 0).

2021-05-14 11:26 UTC, koivunej commented on crates/interledger-stream/src/error.rs
> +    IplPacketType(#[from] IlpPacketTypeError),
```suggestion
    IlpPacketType(#[from] IlpPacketTypeError),
```
Was about to suggest `InnerPacketType` but then I was wondering if it was the inner or outer again. I'm leaning on it being the outer. Might be a good one to comment what this is..

2021-05-14 11:26 UTC, koivunej commented on crates/interledger-stream/src/error.rs
> +    Utf8Err(#[from] Utf8Error),
When does this happen?

2021-05-17 05:40 UTC, whalelephant commented on crates/interledger-stream/src/error.rs
> +    IplPacketType(#[from] IlpPacketTypeError),
Note sure what is inner / outer here. It is the same `PacketType` parsed in interledger-packet/packet.rs. I think these are explicitly ILP PacketType.

2021-05-17 05:40 UTC, whalelephant commented on crates/interledger-stream/src/error.rs
> +    Utf8Err(#[from] Utf8Error),
There are `str` conversion for some frame types, `StreamCloseFrame`, `ConnectionCloseFrame` etc.

2021-05-17 05:40 UTC, whalelephant commented on crates/interledger-stream/src/packet.rs
> +            return Err(StreamPacketError::UnsupportedVersion);
This is related to a previous discussion on `CcpPacketError::UnexpectedCondition` where because `STREAM_VERSION` is a `const` we do not store the compared to value.

2021-05-17 12:24 UTC, koivunej commented on crates/interledger-stream/src/packet.rs
> +            return Err(StreamPacketError::UnsupportedVersion);
Oki. I think there might still be value in keeping the "user provided" version `u8` even though we always match it to a constant.. At least to keep the messages the same.

2021-05-17 12:27 UTC, koivunej commented on crates/interledger-stream/src/error.rs
> +    IplPacketType(#[from] IlpPacketTypeError),
Interestingly I am not finding this from the [rfc](https://github.com/interledger/rfcs/blob/master/0029-stream/0029-stream.md) either, but there were of course many references to Prepares, Fulfills and Rejects.

2021-05-17 12:31 UTC, koivunej commented on crates/interledger-stream/src/error.rs
> +    Utf8Err(#[from] Utf8Error),
From the rfc it would seem like two cases of human readable errorcode and single place for asset code. Well, probably good to leave it as is for now. I was just thinking the [`std::str::Utf8Error`](https://doc.rust-lang.org/stable/std/str/struct.Utf8Error.html) might not bring much value but at least it shouldn't be more than an `usize` + `Option<u8>`.

2021-05-17 12:57 UTC, whalelephant commented on crates/interledger-packet/src/packet.rs
> +        assert_eq!("Input data is not IA5String characters", &e.to_string());
Kept the messages the same and specific to the `Reject.ErrorCode` as this is a refactor.

2021-05-17 12:58 UTC, whalelephant commented on crates/interledger-stream/src/error.rs
> +    #[error("Error maximum time exceeded since last fulfill")]
This are used in error context. 
Have kept the message the same as this is a refactor

2021-05-17 13:04 UTC, koivunej commented on crates/interledger-ccp/src/packet.rs
> +    IOError,
Discussed on the slack, leaving this to a follow-up PR.

2021-05-17 13:10 UTC, koivunej commented on crates/interledger-ccp/src/packet.rs
> +            return Err(CcpPacketError::UnexpectedCondition(
the `execution_condition` should be made into `&[u8; 32]` instead. wonder if I left there a FIXME already?

2021-05-17 13:15 UTC, koivunej commented on crates/interledger-packet/src/errors.rs
>      ChronoErr(#[from] chrono::ParseError),
Just a note for the follow-ups: I dont think there's any point in carrying this around either. If the timestamp isn't good it doesn't really matter how bad is it. I think chrono::ParseError is quite uninformative as well.

2021-05-17 13:16 UTC, whalelephant commented on crates/interledger-ccp/src/packet.rs
> +            return Err(CcpPacketError::UnexpectedCondition(
You left a [comment] in the code.

[comment]: https://github.com/interledger-rs/interledger-rs/pull/722/files#diff-ec91192e65045112abc93b4d8dbe90acace4df9e7e4b2e8abd0ca457e721fb07R220

2021-05-17 13:16 UTC, koivunej commented on crates/interledger-packet/src/packet.rs
> +        return Err(PacketTypeError::Unexpected(got_type, packet_type as u8).into());
Probably would not have harmed to leave the expected as PacketType, or did you check if there was some difference?

2021-05-17 13:17 UTC, koivunej commented on crates/interledger-packet/src/packet.rs
>              &PacketType::try_from(&[][..]).unwrap_err().to_string()
I think this is an okay change.

2021-05-17 13:19 UTC, koivunej commented on crates/interledger-stream/src/client.rs
> +                            .to_owned(),
using `String::from_utf8_lossy(reject.message()).to_owned()` might be better because the `unwrap_or_default()` will default to empty `&'static str`.
```suggestion
                        String::from_utf8_lossy(reject.message())
                            .into_owned(),
```

2021-05-17 13:27 UTC, koivunej commented on crates/interledger-ccp/src/packet.rs
> +            return Err(CcpPacketError::UnexpectedCondition(
Yes I did.

2021-05-17 13:28 UTC, koivunej commented on crates/interledger-ccp/src/packet.rs
>          if prepare.execution_condition() != PEER_PROTOCOL_CONDITION {
Interesting aside note: This check is duplicated along with it's log stmt... Probably not great to log and return an error but ok to clean this up later.

2021-05-17 13:31 UTC, koivunej commented on crates/interledger-packet/src/packet.rs
> +        return Err(PacketTypeError::Unexpected(got_type, packet_type as u8).into());
Well, no need to anything now since this (u8, u8) was repeated in btp at least.

2021-05-17 13:34 UTC, koivunej commented on crates/interledger-stream/src/error.rs
> +    SendMoneyPacket(ErrorCode, String),
Was thinking maybe this should be something like `UnexpectedReject` or similar...? As in: Send money is the operation, and if and it can be stopped with unexpected reject?

2021-05-17 13:35 UTC, koivunej commented on crates/interledger-stream/src/error.rs
>  pub enum Error {
The prefixes went away here but so I guess that means that there are no tests in the interledger-stream for error cases?

2021-05-17 13:37 UTC, koivunej approved these changes
I think this is looking great! Much less `format!(...)`.

As discussed the `std::io::Error` will be gotten rid from `interledger-packet/src/oer.rs` with a more specific simpler enum in a follow-up.

2021-05-17 13:38 UTC, koivunej commented on crates/interledger-stream/src/error.rs
> +    IplPacketType(#[from] IlpPacketTypeError),
Well, lets just leave it like this.

2021-05-17 13:39 UTC, koivunej commented on crates/interledger-packet/src/packet.rs
>              &PacketType::try_from(&[][..]).unwrap_err().to_string()
... since I added the None case when I started fuzzing in #690 I think.

2021-05-17 13:40 UTC, koivunej commented on crates/interledger-stream/src/client.rs
> +                            .to_owned(),
However with the lossy it might be better to format with the `{:?}` since it will escape any control chars... Did this one have a test?

2021-05-18 06:57 UTC, whalelephant commented on crates/interledger-stream/src/error.rs
> +    SendMoneyPacket(ErrorCode, String),
I agree and since we match to other `ErrorCode`, this is an unexpected rejection

2021-05-18 07:22 UTC, whalelephant commented on crates/interledger-stream/src/client.rs
> +                            .to_owned(),
Yes, it does test but only `assert!(result.is_err())` for unexpected reject 
https://github.com/interledger-rs/interledger-rs/pull/722/files#diff-cdf957aff976c708dad406b806a72a2820bfe77c49895c064783bbb117d202fcR773

2021-05-18 07:38 UTC, whalelephant commented on crates/interledger-stream/src/error.rs
>  pub enum Error {
Yes, but also the error message for `SendMoneyError` previously was incorrect.
For example, for external interface, the PaymentFailFast message was 
`Error polling: Terminating payment since too many packets are rejected (x packets fulfilled, y packets rejected)`

Therefore I have removed the prefix and used the same `String` messages.

2021-05-18 07:50 UTC, koivunej commented on crates/interledger-stream/src/error.rs
>  pub enum Error {
Oki, well that makes sense for me! Resolving this one.

2021-05-18 08:02 UTC, koivunej commented on crates/interledger-stream/src/client.rs
> +                            .to_owned(),
All right, looks good! Resolving.

2021-05-18 08:07 UTC, koivunej commented
The latest `test-md` fail is bening installation failure, no worries there.

2021-05-18 08:37 UTC, koivunej commented
Rerunning as the other one failed to start as well.

2021-05-18 09:10 UTC, koivunej commented
Github actions is having issues, we'll need to restart later.

2021-05-19 06:55 UTC, merged