Io errors
interledger-rs/interledger-rs pull request #723
Opened 2021-05-19 10:37 UTC by whalelephant

2021-05-19 16:24 UTC, koivunej reviewed
I think this is looking great! The major question is to go with the added `read_{u{8,16,32},exact}` or just with `bytes::Buf` methods and have an oblig length check before deserialization.

I think the single big length check would be preferable, because afterwards the LLVM can probably see that the `bytes::Buf` methods cannot panic.

Regarding the failed `exchange_rates.rs` test... We might need to disable it, unless there was just some temporary issue.

2021-05-19 16:24 UTC, koivunej commented on crates/interledger-packet/src/errors.rs
> +    UnexpectedBytes,
How are these two different?

2021-05-19 16:24 UTC, koivunej commented on crates/interledger-packet/src/errors.rs
> +    UnexpectedBytes,
the only place I can find is the `read_var_octet_length` for the UnexpectedBytes, but I think the issue will be the same?

As in with input `0x80 | 1, x` where `0 <= x < 128` the initial byte should had been used for the length as it would had fit. I think this part is quite explicit in the RFC: https://github.com/interledger/rfcs/blob/master/0030-notes-on-oer-encoding/0030-notes-on-oer-encoding.md#long-form

Aah yes but now I understand, the messages were different, so two variants were created. I think that two distinct variants makes sense. The `LeadingZeros` could even be `#[cfg(feature = "strict")]` which should not be an issue.

Wonder if the `UnexpectedBytes` be more fitting with `UnexpectedLongForm` (per rfc?) or could just have two LeadingZeros:
- LeadingZeros -- could explicitly link to the rfc's "Long form" header
- StrictLeadingZeros -- only in strict, I guess this would be the ref: https://github.com/interledger/rfcs/blob/master/0030-notes-on-oer-encoding/0030-notes-on-oer-encoding.md#variable-length-unsigned-integer even though it says it's not used...

2021-05-19 16:24 UTC, koivunej commented on crates/ilp-node/Cargo.toml
> -tokio-retry = { version = "0.2.0", default-features = false }
Very nice finds! Big win here already for tokio upgrading..

2021-05-19 16:24 UTC, koivunej commented on crates/interledger-btp/src/errors.rs
> +    UnexpectedEof,
This would duplicate the `Oer(OerError::UnexpectedEof)` and similarly in others but I guess this is for the different string...?

2021-05-19 16:28 UTC, koivunej commented on crates/interledger-packet/src/packet.rs
> +        // This will always return since content was returned by read_var_octet_string
Might be good to recheck the fuzzing on this one either way. If we don't find a fast panic then something is wrong with the fuzz target or on my reading comprehension.

2021-05-19 18:29 UTC, koivunej commented on crates/interledger-packet/src/packet.rs
> +        // This will always return since content was returned by read_var_octet_string
`[12, 0]` will also hit a panic in this line.

2021-05-20 06:55 UTC, whalelephant commented on crates/interledger-btp/src/errors.rs
> +    UnexpectedEof,
Yes for the string but also the check for packet length in this case is done in this crate, not code in `Oer`.

2021-05-20 09:14 UTC, whalelephant commented on crates/interledger-packet/src/packet.rs
> +        // This will always return since content was returned by read_var_octet_string
you are correct. This does not always return and need to be checked.

2021-05-20 09:26 UTC, whalelephant commented on crates/interledger-packet/src/errors.rs
> +    Error,
removed

2021-05-20 14:25 UTC, koivunej commented on crates/interledger-ccp/src/packet.rs
> +        let from_epoch_index = data.get_u32();
Crash here with the fuzz_target_2: `[10, 255, 255, 255, 255, 159, 159, 159, 159, 49, 10, 255, 10, 159, 159, 159, 46, 255, 255, 255]`.

The min length should be at least: 16 where it's currently 2 for the routing table id, then there should also be one for the Address or read_var_octet_string (0 is the minimum payload for that).

So up until Address there should be 16 + 4 + 4 + 4 + 4 + 1, after that I think a "+ 2" can be added (minimum varuint) and after that it's more complicated. If the routes were simple I would had done the preallocation checks here as well.

2021-05-20 14:27 UTC, koivunej commented on crates/interledger-ccp/src/packet.rs
> +        if data.remaining() < 2 + 4 + 4 + 4 + 4 {
```suggestion
        // RouteUpdateRequest: routing_table_id (16)
        // + current_epoch_index (4)
        // + from_epoch_index (4)
        // + to_epoch_index (4)
        // + hold_down_time (4)
        // + address (1, too low bound)
        // + var uint (2, correct low bound)
        if data.remaining() < 16 + 4 + 4 + 4 + 4 + 1 + 2 {
```

2021-05-20 14:29 UTC, koivunej commented on crates/interledger-ccp/src/packet.rs
> +        // RouteControlRequest: mode (4) + last_known_routing_table_id (16) + last_known_epoch (4)
```suggestion
        // RouteControlRequest: mode (1) + last_known_routing_table_id (16) + last_known_epoch (4)
```

2021-05-20 14:31 UTC, koivunej approved these changes
With the suggestions I think this is looking good!

2021-05-20 14:32 UTC, koivunej commented on crates/interledger-ccp/src/packet.rs
> +        let from_epoch_index = data.get_u32();
Could you add the crash as a test case?

2021-05-20 15:38 UTC, koivunej commented on crates/interledger-ccp/src/packet.rs
> +        if data.remaining() < 2 + 4 + 4 + 4 + 4 {
Resolving, as I pr'd the changes: https://github.com/whalelephant/interledger-rs/pull/1

2021-05-20 15:38 UTC, koivunej commented on crates/interledger-ccp/src/packet.rs
> +        // RouteControlRequest: mode (4) + last_known_routing_table_id (16) + last_known_epoch (4)
Resolving as I pr'd: https://github.com/whalelephant/interledger-rs/pull/1

2021-05-20 15:39 UTC, koivunej commented on crates/interledger-ccp/src/packet.rs
> +        let from_epoch_index = data.get_u32();
Added in https://github.com/whalelephant/interledger-rs/pull/1.

2021-05-21 09:21 UTC, koivunej commented on crates/interledger-service-util/src/echo_service.rs
> +            eprintln!("Could not read packet type: Unexpected Eof");
This is a rather interesting one. I would assume that this was supposed to be an `error!`, there are also some similar cases in other crates. Can PR this in once we have merged this PR.

2021-05-21 09:23 UTC, koivunej commented
Oki I understand that the PR is now ready to be merged.

2021-05-21 14:24 UTC, pradovic requested changes
Great job!
I added a couple of subjective comments, so if you don't agree with them you can skip, it is still good to go from me!

2021-05-21 14:24 UTC, pradovic commented on crates/interledger-btp/src/errors.rs
> +    #[error("Oer Error: {0:?}")]
I would maybe omit the word `Error` from errors here and where formatting as well. 
The reason for this is subjective so feel free to ignore if you don't agree. The reason being, in my mind, is that it is of an Error enum, so we know that it is an Error + if it ends up being printed it is usually in `error!()` so it will have an error scope anyways.

2021-05-21 14:24 UTC, pradovic commented on crates/interledger-btp/src/packet.rs
> +        if reader.remaining() < 1 + 4 {
I would maybe extract 1 and 4 as constants and use it, together with a comment. This also makes it more sensical from the doc standpoint, imo.

2021-05-21 14:24 UTC, pradovic commented on crates/interledger-btp/src/packet.rs
> +        if reader.remaining() < 1 + 4 {
Same as above :)

2021-05-21 14:24 UTC, pradovic commented on crates/interledger-btp/src/packet.rs
> +        if reader.remaining() < 1 + 4 {
Same as above :)

2021-05-21 14:24 UTC, pradovic commented on crates/interledger-ccp/src/packet.rs
> +            CcpPacketError::Oer(err) => write!(fmt, "Oer Error {:?}", err),
Same comment for formatting as the one above, maybe remove `Error` word.

2021-05-21 14:24 UTC, pradovic commented on crates/interledger-ccp/src/packet.rs
> +        if data.remaining() < 1 + 16 + 4 {
Similar to the above comment, these could be constants.

2021-05-21 14:24 UTC, pradovic commented on crates/interledger-ccp/src/packet.rs
> +        if data.remaining() < 1 + 2 {
Same as above.

2021-05-21 14:24 UTC, pradovic commented on crates/interledger-packet/src/errors.rs
> +    #[error("Oer Error: {0}")]
Same as above about the  word :)

2021-05-21 14:24 UTC, pradovic commented on crates/interledger-packet/src/errors.rs
>      #[error("PacketType Error: {0}")]
I know it';s not part of this PR but we could ommit the `Error` word here as well.

2021-05-21 14:26 UTC, koivunej commented on crates/interledger-btp/src/errors.rs
> +    #[error("Oer Error: {0:?}")]
I had missed this one and I think we need to align the how the OerError is formatted; as in it's `{}` in the latter two and `{:?}` in the first two.

2021-05-21 14:28 UTC, pradovic commented on crates/interledger-btp/src/errors.rs
> +    #[error("Oer Error: {0:?}")]
@koivunej correct, I have missed this as well!

2021-05-21 14:28 UTC, koivunej commented on crates/interledger-packet/src/errors.rs
>      #[error("PacketType Error: {0}")]
This was added in the prev PR #722 so should be good to alter; however there's an argument to be made for keeping it as others have as well... In generally I think we should try not to change error messages when refactoring as those could be dependended on log scanners and possibly used in interfaces like http.

2021-05-24 10:24 UTC, koivunej commented on crates/interledger-btp/src/errors.rs
> +    #[error("Oer Error: {0:?}")]
I remember wondering on the weekend that "Oer Error" with or without "Error" might not be so clear on the logs. It could be restored to "Invalid Packet: $reason", which it used to be.

2021-06-10 16:17 UTC, koivunej commented on crates/interledger-btp/src/errors.rs
> +    #[error("Oer Error: {0:?}")]
I'll resolve these as I've now PR'd whalelephant these fixes.

2021-06-10 16:32 UTC, koivunej commented on crates/interledger-btp/src/packet.rs
> +        if reader.remaining() < 1 + 4 {
extracted soon in a commit I'll push once tested.

2021-06-10 16:32 UTC, koivunej commented on crates/interledger-ccp/src/packet.rs
> +            CcpPacketError::Oer(err) => write!(fmt, "Oer Error {:?}", err),
Replaced with "older" (dunno if really) `Invalid Packet: {}`

2021-06-15 08:54 UTC, pradovic approved these changes
LGTM! 👏  nice job!

2021-06-15 09:11 UTC, koivunej commented
Cannot get any reliable perf changes, but at least there's no more IO error, so this is a big win for readability.

2021-06-15 09:11 UTC, merged